import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import dynamic from "next/dynamic";

import "./globals.css";

import { auth } from "@/auth";

import TopHeader from "@/components/top-header";
import Footer from "@/components/footer";
import { Toaster } from "@/components/ui/toaster";

import { TanstackProvider } from "@/providers/tanstack-provider";
import { CartProvider } from "@/providers/cart-provider";

const Navbar = dynamic(() => import("@/components/navbar"), { ssr: false });

const poppins = Poppins({ weight: "500", subsets: ["latin-ext"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={poppins.className}>
          <Toaster />
          <TanstackProvider>
            <CartProvider>
              <TopHeader />
              <Navbar />
              <div className="flex-1">{children}</div>
              <Footer />
            </CartProvider>
          </TanstackProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
